include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - validate # fmt, validate, lint
  - test # secret detection
  - security # checkov

terraform-fmt:
  stage: validate
  image:
    name: hashicorp/terraform:1.16
    entrypoint: [""]
  script: terraform fmt -check -recursive terraform/

terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.16
    entrypoint: [""]
  script:
    - cd terraform
    - terraform init -backend=false
    - terraform validate

ansible-lint:
  stage: validate
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir ansible-lint
    - cd ansible
    - ansible-galaxy collection install -r requirements.yaml
  script:
    - ansible-lint

tflint:
  stage: validate
  image:
    name: ghcr.io/terraform-linters/tflint
    entrypoint: [""]
  script:
    - cd terraform
    - tflint --recursive

checkov:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d terraform --framework terraform
  allow_failure: true
