include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - validate # fmt, validate, lint
  - test # secret detection
  - security # checkov
  - plan

terraform-fmt:
  stage: validate
  image:
    name: hashicorp/terraform:1.16
    entrypoint: [""]
  script: terraform fmt -check -recursive terraform/

terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.16
    entrypoint: [""]
  script:
    - cd terraform
    - terraform init -backend=false
    - terraform validate

ansible-lint:
  stage: validate
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir ansible-lint
    - cd ansible
    - ansible-galaxy collection install -r requirements.yaml
  script:
    - ansible-lint

tflint:
  stage: validate
  image:
    name: ghcr.io/terraform-linters/tflint
    entrypoint: [""]
  script:
    - cd terraform
    - tflint --recursive

checkov:
  stage: security
  image:
    name: bridgecrew/checkov:3.3.19
    entrypoint: [""]
  script:
    - checkov -d terraform --framework terraform

terraform:plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.16
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDCC_TOKEN:
      aud: "api://AzureADTokenExchange"
  variables:
    ARM_USE_OIDC: "true"
    ARM_OIDC_TOKEN: "{GITLAB_OIDC_TOKEN}"
    TF_ROOT: "terraform"
  before_script:
    - cd "${TF_ROOT}"
    - terraform init -backend=false
  script:
    - terraform plan -var-file="terraform.tfvars.example"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
