- name: Request Azure access token from IMDS
  ansible.builtin.uri:
    url: "{{ keyvault_secret_imds_token_url }}?api-version={{ keyvault_secret_imds_api_version }}&resource={{ keyvault_secret_resource | urlencode }}"
    method: GET
    headers:
      Metadata: "true"
    status_code: 200
  register: keyvault_secret_imds_response
  changed_when: false
  no_log: true

- name: Fetch secret value from Key Vault
  ansible.builtin.uri:
    url: "{{ keyvault_uri }}/secrets/{{ keyvault_secret_name }}?api-version={{ keyvault_secret_api_version }}"
    method: GET
    headers:
      Authorization: "Bearer {{ keyvault_secret_imds_response.json.access_token }}"
    status_code: 200
  register: keyvault_secret_response
  retries: 5
  delay: 10
  until: keyvault_secret_response is succeeded
  changed_when: false
  no_log: true

- name: Set db_password fact # noqa: var-naming[no-role-prefix]
  ansible.builtin.set_fact:
    db_password: "{{ keyvault_secret_response.json.value }}"
    cacheable: false
  no_log: true
