- name: Apply common hardening and base configuration
  hosts: all
  become: true
  roles:
    - common

- name: Configure database server
  hosts: db
  become: true
  roles:
    - keyvault_secret
    - db

- name: Configure application server
  hosts: back
  become: true
  roles:
    - keyvault_secret
    - app

- name: Configure reverse proxy
  hosts: front
  become: true
  roles:
    - nginx
