- name: Apply common hardening and base configuration
  hosts: all
  become: true
  roles:
    - common

- name: Configure database server
  hosts: db
  become: true
  roles:
    - db

- name: Configure application server
  hosts: back
  become: true
  roles:
    - app
